### ISSUE TITLE
Issue with Material Transparency

### ISSUE THREAD

**Issue by srivastava-abhishek-iceman** [hoverinc/ray-tracing-renderer#115]
Hi,

I have been having trouble with getting glass material to appear transparent. I am attaching the files before and after rendering. The material that I've used is below and the material does become transparent when raytracing. However, the items behind this glass material aren't visible. Any solution to this?

new THREE.MeshStandardMaterial({transparent: true});

![WebGLRenderer](https://user-images.githubusercontent.com/65914707/82867825-1f9c7e00-9f49-11ea-9862-fa75e57374c3.png)

![RayTracingRenderer](https://user-images.githubusercontent.com/65914707/82867820-1dd2ba80-9f49-11ea-95c5-2f87dae23eed.png)

**Comment by nicolab28** [comment]
You must use
`
material.transparent = true;
material.solid = true;
`
with a RayTracingMaterial
[https://github.com/hoverinc/ray-tracing-renderer/wiki/RayTracingMaterial](url)

**Comment by srivastava-abhishek-iceman** [comment]
> You must use
> `material.transparent = true; material.solid = true;`
> with a RayTracingMaterial
> https://github.com/hoverinc/ray-tracing-renderer/wiki/RayTracingMaterial

Thanks for the reply @nicolab28 . However, I've tried doing that and it didn't work out either.
This is what I used.
        const material1 = new THREE.RayTracingMaterial();
        material1.transparent=true;
        material1.solid=true;

And this is the result. Any help is welcome. I've been stuck here for quite some time now..

![Result3](https://user-images.githubusercontent.com/65914707/82919656-f0f7c500-9f93-11ea-9f35-30ebd079b82c.png)

**Comment by nicolab28** [comment]
have you tested with another shape like a flattened sphere, or slightly spherized your plan?

**Comment by nicolab28** [comment]
Or pass me your piece of code that generates these objects

**Comment by srivastava-abhishek-iceman** [comment]
I have so far tried this with 2 geometries - BoxBufferGeometry and ExtrudeGeometry. Neither worked. My actual project is quite big. But that involves a transparent glass material and hence I made a testing app on Flask. I am writing the code below. You can replace the static resources with your own. I am attaching the testing code file in txt and also trying to replicate the code here.

`
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Testing App</title>
    <style>
        body { margin: 0; }
        canvas { display: block; }
        .ui{
            position: absolute;
            top:0;
        }
    </style>
</head>
<body>
<script src="{{ url_for('static', filename='js/three.js') }}"></script>
<script src="{{ url_for('static', filename='js/RGBELoader.js') }}"></script>
<script src="{{ url_for('static', filename='js/OrbitControls.js') }}"></script>
<script src="{{ url_for('static', filename='js/RayTracingRenderer.js') }}"></script>

<script>
    var scene;
    var camera;
    var renderer;
    function init() {
        renderer = new THREE.WebGLRenderer();
        document.body.appendChild(renderer.domElement);
        scene = new THREE.Scene();
        scene.background = new THREE.Color("rgb(50,50,50)");
        camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 8000);
        scene.add(camera);
        camera.position.set(0, 0, 1000);
        renderer.setSize(window.innerWidth, window.innerHeight);
        var controls = new THREE.OrbitControls(camera, renderer.domElement);
        
        var directionalLight = new THREE.SoftDirectionalLight( 0xffffff, 0.8 );
        scene.add( directionalLight );
        directionalLight.position.set(0,0,1000);
        directionalLight.lookAt(0,0,0);

        var geometry1 = new THREE.BoxBufferGeometry(880,880,6);
        var textureloader = new THREE.TextureLoader();
        var texture = textureloader.load("{{url_for('static', filename='textures/pine.jpg')}}");
        texture.encoding = THREE.sRGBEncoding;
        
        const material1 = new THREE.RayTracingMaterial();
        material1.transparent=true;
        material1.solid=true;

        var mesh1 = new THREE.Mesh(geometry1, material1);
        mesh1.position.x = 400;
        mesh1.position.y = 400;
        mesh1.position.z = 100;
        scene.add(mesh1);


        var material2 = new THREE.MeshStandardMaterial({map: texture});

        var geometry2 = new THREE.BoxBufferGeometry(1000,1000,400);
        var mesh2 = new THREE.Mesh(geometry2, material2);
        mesh2.position.z = -500;
        scene.add(mesh2);
        

    }
    //Animating the Scene
    function animate() {
        requestAnimationFrame( animate );
        renderer.render( scene, camera );
    }

    init();
    animate();

    function changerenderer(){
        var raytracingrenderer = new THREE.RayTracingRenderer();
        raytracingrenderer.setSize(window.innerWidth, window.innerHeight);
        document.body.removeChild(renderer.domElement);
        document.body.appendChild(raytracingrenderer.domElement);

        function realism() {
                raytracingrenderer.render( scene, camera );
                requestAnimationFrame( realism );
            }
        THREE.DefaultLoadingManager.onLoad = realism();
    }
</script>
<button class="ui" onclick="changerenderer();">Click</button>
</body>
</html>
`


[testing_app.txt](https://github.com/hoverinc/ray-tracing-renderer/files/4683484/testing_app.txt)

**Comment by nicolab28** [comment]
try 
`renderer.bounces = 6;`

**Comment by nicolab28** [comment]
I think you have an initialization problem, remove all your part of webglrenderer, and with the bounce at 6 it works.
What is the purpose of changerenderer ()?

**Comment by srivastava-abhishek-iceman** [comment]
Thanks for the help. The purpose of changerenderer() was to basically display the raytraced image in the same browser window. I figured that would be a good way to quickly switch between my editing environment (WebGL Renderer) and the image output (RayTracingRenderer).

**Comment by srivastava-abhishek-iceman** [comment]
Really appreciate your help @nicolab28 .
I'll close this thread now and go back to working on my project.
