### ISSUE TITLE
Using threejs renderer and raytracing renderer in the same canvas

### ISSUE THREAD

**Issue by VinAr22** [hoverinc/ray-tracing-renderer#128]
Hello! Can I use Threejs Renderer and Raytracing Render on the same canvas without deleting it? I got an error when I tried. I use your [example ](https://hoverinc.github.io/ray-tracing-renderer/scenes/webgl-comparison/)  for this. 
Thank you !

P.s i tried your renderer with React library. so far everything is working

**Comment by VinAr22** [comment]
I set the webgl2 context for my webgl renderer, it works but not perfect. If I move the camera, the image becomes foggy. I think because webgl rendering creates buffers that differ in the ray tracing renderers. Is there any way how to solve my problem?

**Comment by elfrank** [comment]
@VinAr22 a canvas can only have one WebGL context attached to it at any time.

It is possible to use the same canvas to run `WebGLRenderer` and `RayTracingRenderer,` but only one `WebGLContext` can be attached to the canvas at a time. You would need to swap them or to have one canvas for each Renderer.

Does that make sense?

**Comment by VinAr22** [comment]
Hello @elfrank!  Thanks for the answer, yes, that makes sense, because I use a react library whose main idea is minimal redraw the dom.  This is not very good when the dom element is deleted and created again, much faster the change of render occurs inside one canvas.  however, I already wrote that this does not work correctly, maybe you have any ideas on this? Thank you!

**Comment by elfrank** [comment]
@VinAr22 you can have two `div` elements, each with a different `canvas` element.

You don't need to delete the `div`, you could:

1. hide them using CSS such as `visibility: hidden`, or
2. you could [remove elements](https://www.abeautifulsite.net/adding-and-removing-elements-on-the-fly-using-javascript) from the DOM on the fly. I'm not well versed in React but a quick Google Search threw [this](https://stackoverflow.com/questions/51412139/how-do-you-swap-out-a-component-in-react).

**Comment by elfrank** [comment]
Closing the issue as the original question was answered [here](https://github.com/hoverinc/ray-tracing-renderer/issues/128#issuecomment-655194263)
