### ISSUE TITLE
Unable to run demo: Failed to execute 'getActiveUniforms' on 'WebGL2RenderingContext'

### ISSUE THREAD

**Issue by carstenschwede** [hoverinc/ray-tracing-renderer#134]
I am unable to run the demo [here](https://hoverinc.github.io/ray-tracing-renderer/scenes/sample-models/):

```
Failed to execute 'getActiveUniforms' on 'WebGL2RenderingContext': The provided value cannot be converted to a sequence.
```

But this [one](https://hover-demos.s3.amazonaws.com/ray-tracing-renderer/readme-example/index.html) works.

**Comment by elfrank** [comment]
> I am unable to run the demo [here](https://hoverinc.github.io/ray-tracing-renderer/scenes/sample-models/):
> 
> ```
> Failed to execute 'getActiveUniforms' on 'WebGL2RenderingContext': The provided value cannot be converted to a sequence.
> ```
> 
> But this [one](https://hover-demos.s3.amazonaws.com/ray-tracing-renderer/readme-example/index.html) works.

on what browser?
on what OS?
on what device?
on the device that triggers that error, what's the output from https://webglreport.com/?v=2 ? See https://github.com/hoverinc/ray-tracing-renderer/issues/97 for an example.

**Comment by carstenschwede** [comment]
Here you go, let me know if you need additional info:

![Screen Shot 2020-07-08 at 10 30 57](https://user-images.githubusercontent.com/234960/86896415-374d5180-c106-11ea-8158-bd863378bc14.png)

**Comment by carstenschwede** [comment]
Seems to be specific to the GTX970. Error does not appear on either a RX 5400M or RX 5600M. Closing since I won't be able to test on a GTX970 anymore.

<img width="915" alt="Screenshot 2020-07-23 at 16 02 16" src="https://user-images.githubusercontent.com/234960/88295619-f35d6d80-ccfd-11ea-9f92-ce6d3c5a12ac.png">

**Comment by elfrank** [comment]
@carstenschwede thanks for the update!

**Comment by elfrank** [comment]
@carstenschwede thanks for the update!
