### ISSUE TITLE
Flickering raytracer with offsetting hdr

### ISSUE THREAD

**Issue by ManishJu** [hoverinc/ray-tracing-renderer#64]
The renderer is flickering and the hdr background is displaced to a large amount when the renderer is built with threejs 112.

Here is the video: 
[screenrecord.zip](https://github.com/hoverinc/ray-tracing-renderer/files/4104323/screenrecord.zip)

No error in console, just warnings. Hope this helps!.

**Comment by jaxry** [comment]
Very interesting bug. I'm not sure what's going on so I have a few questions.

* Does the scene render correctly when using a lower version of threejs? 
* If you open `scenes/renderer-test/main.js` and change line 6 to `renderer.maxHardwareUsage = false;`, does it run correctly?
* Are you able to reproduce the bug when loading the scene on another device? 

I'm also developing on threejs 112, and this scene, as well as the others, render fine on the devices I'm using. So I'm worried this might be a device-dependent bug.

**Comment by jaxry** [comment]
I'll close this ticket for now, but if you're still experiencing the issue, please let me know.
