### ISSUE TITLE
Use ray tracing renderer with react

### ISSUE THREAD

**Issue by VinAr22** [hoverinc/ray-tracing-renderer#82]
Hello! Is it possible to use your renderer in react app?

**Comment by jaxry** [comment]
I'm not sure since I haven't used React before. What's needed of the renderer as a dependency to use in a React app?

**Comment by VinAr22** [comment]
Hello! Sorry, did not see your answer. I have not tried to use your renderer with react yet. 



Have you seen this project? https://erichlof.github.io/THREE.js-PathTracing-Renderer/ 

how much are your algorithms different? Can you partially borrow the code for your tasks?

**Comment by jaxry** [comment]
>I have not tried to use your renderer with react yet.

In that case, I'll close this issue. If you have problems with React, let me know!

>how much are your algorithms different? Can you partially borrow the code for your tasks?

Interesting project! It implements a lot more advanced path tracing features (volumetric lighting, bi-directional path tracing), but unfortunately those algorithms aren't compatible with denoising, which is what we're moving towards.

**Comment by VinAr22** [comment]
Hi @jaxry! I found another interesting project
https://github.com/kantedal/pathtracer-webgl2
