### ISSUE TITLE
the build of the build folder is not identical to an npm run build

### ISSUE THREAD

**Issue by nicolab28** [hoverinc/ray-tracing-renderer#90]
I have normal's problem, on flat glass surfaces, when I build by doing an npm run build.
I compared the files and there is indeed code that changes. Not a lot, but there are.
Some screenshots:

With the js file, from the build directory
![from the fork](https://user-images.githubusercontent.com/56133081/81201275-64c23580-8fc5-11ea-8b6d-488064ee8b3e.jpg)

when i do a npm run
![npm run build](https://user-images.githubusercontent.com/56133081/81201281-65f36280-8fc5-11ea-9d04-03eb07f243fd.jpg)

**Comment by jaxry** [comment]
Thanks for the bug report. This is the same issue as https://github.com/hoverinc/ray-tracing-renderer/issues/92, so I'll redirect us there :)
