### ISSUE TITLE
RayTracingRenderer.js:1650 Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by michealChin** [hoverinc/ray-tracing-renderer#91]
Hi,

I load a wavefront file that have 58 mesh within it. I replace the exiting mesh material with MeshStandardMaterial, but the application throw this Uncaught RangeError: Maximum call stack size exceeded exception. If I run a simple Cube example, the RayTracingRenderer can render without any problem. Any possible reason?

**Comment by jaxry** [comment]
I think you might be experiencing the bug fixed in this PR https://github.com/hoverinc/ray-tracing-renderer/pull/81

We haven't updated the build yet so the fix isn't in effect. Let me try to publish the build ASAP and hopefully that fixes your issue.

**Comment by jaxry** [comment]
Does the latest build resolve the issue?

**Comment by michealChin** [comment]
Yes, the latest release works!
