### ISSUE TITLE
How to detect hardware/software compatibility?

### ISSUE THREAD

**Issue by nicolab28** [hoverinc/ray-tracing-renderer#97]
I'm trying to find a method to test the hardware compatibility, and stop the process if not compatible, but impossible to find a solution ...
I tested the canvas with the method

gl = renderer.domElement.getContext ("webgl2");
alert (gl.getParameter (gl.VERSION));

And it returns me well "WebGL2 OpenGL ES 3.0", while I have a black background on my smartphone ... Stats shows me the FPS, but black background.

I also tested: https://get.webgl.org/webgl2/ and I have the cube spinning.

How do you do? Because on an old PC, this completely blocks the machine, forced to do a reset

**Comment by elfrank** [comment]
> I'm trying to find a method to test the hardware compatibility, and stop the process if not compatible, but impossible to find a solution ...
> I tested the canvas with the method
> 

@nicolab28 , you can use the `isSupported()` method on the `RayTracingRenderer` instance. See https://github.com/hoverinc/ray-tracing-renderer/blob/cfb68519156e6526d1d90fae1b378c5637f25ba7/src/RayTracingRenderer.js#L178

Caveat: Note that it is a hardware check. We have noticed that some hardware "passes" the check but performance is poor.

Hope that helps :)

**Comment by nicolab28** [comment]
thank you,
I had not seen this function, but my smartphone passes the test without displaying anything ...

**Comment by elfrank** [comment]
> thank you,
> I had not seen this function, but my smartphone passes the test without displaying anything ...

1. What phone do you have?
2. What's the version of your operating system?
3. Could you upload the output of this page? https://webglreport.com/?v=2

**Comment by nicolab28** [comment]
It's a Xiaomi Mi Mix 2, Snapdragon 835, de 4 Go
![captureWebGL](https://user-images.githubusercontent.com/56133081/82155856-0d02b480-9878-11ea-8fe7-4ba96b446cf9.jpg)

**Comment by nicolab28** [comment]
I just tested with the chrome remote debugger, on my smartphone, and the console tells me, just after the first sample:
WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost

**Comment by elfrank** [comment]
@nicolab28 sorry for the late response, I need to update my notifications settings. I missed this somehow.

Were you able to figure it out? It seems like an "insufficient memory" problem but I could be wrong.

The WebGL 2 support on Android seems to need some more polish from some device testing I did a few months back.

**Comment by nicolab28** [comment]
I don't think this is a memory problem, because even with a simple cube, it loses context.
Unless this is an environment map problem?
One thing is sure, I did not manage to make the examples work, either on my smartphone, or on a galaxy tab

**Comment by elfrank** [comment]
@nicolab28 I'm going to close this issue as the original question was around detecting hardware/software compatibility.

Feel free to submit an issue with the bug you mentioned (affecting your smartphone and galaxy tab). We don't have the bandwidth to look into it at the moment, but it might be helpful for others facing a similar issue.
